### ISSUE TITLE
publisher stuck reconnecting

### ISSUE THREAD

**Issue by blalor** [driskell/log-courier#100]
My logstash server -- with the `courier` input plugin -- was down for a few days over the long weekend due to a disk filling up.  Since then I've noticed that my overall log event rate has been considerably lower than it was before the server crashed.  I isolated one particular server that has stopped sending logs.  The output of `lc-admin status` is below:

```
# lc-admin -connect unix:///var/run/log-courier/admin.socket status
Log Courier version 1.3 client

Attempting connection to unix:///var/run/log-courier/admin.socket...
Connected

"State: /var/log/logstash/canaryio.log (0xc20809cfc0)":
  Status: Running
  Harvester:
    Speed (Lps): 1024.00
    Speed (Bps): 485451.00
    Processed lines: 10390689
    Current offset: 401885555
    Last EOF Offset: 399937855
    Status: Alive
"State: /var/log/supervisor/supervisord.log (0xc20809c120)":
  Status: Running
  Harvester:
    Speed (Lps): 0.00
    Speed (Bps): 0.00
    Processed lines: 53
    Current offset: 4571
    Last EOF Offset: 4518
    Status: Idle
    Dead timer: 0s
"State: /var/log/syslog.csv (0xc209376240)":
  Status: Running
  Harvester:
    Speed (Lps): 0.00
    Speed (Bps): 0.00
    Processed lines: 0
    Current offset: 216
    Last EOF Offset: Never
    Status: Alive
"State: /var/log/syslog.csv (Orphan / 0xc209376000)":
  Status: Running
  Harvester:
    Speed (Lps): 0.00
    Speed (Bps): 0.00
    Processed lines: 0
    Current offset: 216
    Last EOF Offset: Never
    Status: Alive
"State: /var/log/syslog.csv (Orphan / 0xc209376120)":
  Status: Running
  Harvester:
    Speed (Lps): 0.00
    Speed (Bps): 0.00
    Processed lines: 0
    Current offset: 216
    Last EOF Offset: Never
    Status: Alive
"State: /var/log/syslog.csv (Orphan / 0xc209376fc0)":
  Status: Running
  Harvester:
    Speed (Lps): 0.00
    Speed (Bps): 0.00
    Processed lines: 0
    Current offset: 216
    Last EOF Offset: Never
    Status: Alive
"State: /var/log/syslog.csv (Orphan / 0xc20a3ac540)":
  Status: Running
  Harvester:
    Speed (Lps): 0.00
    Speed (Bps): 0.00
    Processed lines: 875
    Current offset: 180589
    Last EOF Offset: 180394
    Status: Idle
    Dead timer: 0s
Prospector:
  Watched files: 3
  Active states: 7
Publisher:
  Status: Reconnecting...
  Speed (Lps): 0.00
  Published lines: 10386000
  Pending Payloads: 27
  Timeouts: 233
  Retransmissions: 0
```

I've verified that I can connect to the logstash server from the host in question.  The `Status: Reconnecting...` is curious.  There is nothing in the output of `netstat` or `lsof` that shows log-courier attempting to connect to the server.

There's nothing on stdout from log-courier, but I do have syslog enabled; here's what I see around (what appears to be) the time period that log-courier got wedged:

```
2015-01-19 05:42:18.953 log-courier[15]: Attempting to connect to 10.128.85.155:5044 (log-courier.service.consul)
2015-01-19 05:42:18.954 log-courier[15]: Transport init failed: Failed to connect to 10.128.85.155:5044 (log-courier.service.consul): dial tcp 10.128.85.155:5044: connection refused
2015-01-19 05:42:19.960 log-courier[15]: Attempting to connect to 10.128.85.155:5044 (log-courier.service.consul)
2015-01-19 05:42:19.961 log-courier[15]: Transport init failed: Failed to connect to 10.128.85.155:5044 (log-courier.service.consul): dial tcp 10.128.85.155:5044: connection refused
2015-01-19 05:42:20.967 log-courier[15]: Attempting to connect to 10.128.85.155:5044 (log-courier.service.consul)
2015-01-19 05:42:21.073 log-courier[15]: Connected to 10.128.85.155:5044 (log-courier.service.consul)
2015-01-19 05:42:21.073 log-courier[15]: Transport error, will try again: Server did not respond within network timeout
2015-01-19 05:42:22.078 log-courier[15]: Attempting to connect to 10.128.85.155:5044 (log-courier.service.consul)
2015-01-19 05:42:22.141 log-courier[15]: Connected to 10.128.85.155:5044 (log-courier.service.consul)
2015-01-19 05:42:26.841 log-courier[15]: Transport error, will try again: write tcp 10.128.85.155:5044: connection reset by peer
2015-01-20 03:24:24.317 log-courier[15]: Launching harvester on rotated file: /var/log/syslog.csv
2015-01-20 03:24:24.317 log-courier[15]: Started harvester at position 0 (requested 0): /var/log/syslog.csv
2015-01-21 03:36:26.376 log-courier[15]: Launching harvester on rotated file: /var/log/syslog.csv
2015-01-21 03:36:26.376 log-courier[15]: Started harvester at position 0 (requested 0): /var/log/syslog.csv
2015-01-22 03:35:28.376 log-courier[15]: Launching harvester on rotated file: /var/log/syslog.csv
2015-01-22 03:35:28.376 log-courier[15]: Started harvester at position 0 (requested 0): /var/log/syslog.csv
```

Looks like it finally was able to connect and then got stuck after the last disconnection. It hasn't attempted to reconnect again in a few days.

Finally, I did a `kill -ABRT 15` and this is the stack trace:
```
SIGABRT: abort
PC=0x430ef1

goroutine 0 [idle]:
runtime.futex(0x8ab1f0, 0x0, 0x0, 0x0)
    /usr/lib/golang/src/pkg/runtime/sys_linux_amd64.s:268 +0x21
runtime.futexsleep(0x8ab1f0, 0x0, 0xffffffffffffffff)
    /usr/lib/golang/src/pkg/runtime/os_linux.c:49 +0x47
runtime.notesleep(0x8ab1f0)
    /usr/lib/golang/src/pkg/runtime/lock_futex.c:135 +0x86
stopm()
    /usr/lib/golang/src/pkg/runtime/proc.c:954 +0xe0
findrunnable()
    /usr/lib/golang/src/pkg/runtime/proc.c:1262 +0x445
schedule()
    /usr/lib/golang/src/pkg/runtime/proc.c:1345 +0xe3
park0(0xc208061440)
    /usr/lib/golang/src/pkg/runtime/proc.c:1410 +0xfe
runtime.mcall(0x42e087)
    /usr/lib/golang/src/pkg/runtime/asm_amd64.s:181 +0x4b

goroutine 16 [select, 36 minutes]:
main.(*LogCourier).Run(0xc2080042a0)
    BUILD/log-courier-1.3/src/log-courier/log-courier.go:108 +0x762
main.main()
    BUILD/log-courier-1.3/src/log-courier/log-courier.go:43 +0x2b

goroutine 19 [finalizer wait, 18532 minutes]:
runtime.park(0x416320, 0x8a9018, 0x8a7a69)
    /usr/lib/golang/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x8a9018, 0x8a7a69)
    /usr/lib/golang/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
    /usr/lib/golang/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
    /usr/lib/golang/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall, 18532 minutes]:
os/signal.loop()
    /usr/lib/golang/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
    /usr/lib/golang/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 21 [IO wait]:
net.runtime_pollWait(0x7f1fdbe541b0, 0x72, 0x0)
    /usr/lib/golang/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc2080aca70, 0x72, 0x0, 0x0)
    /usr/lib/golang/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc2080aca70, 0x0, 0x0)
    /usr/lib/golang/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc2080aca10, 0x79fab8, 0x0, 0x7f1fdbe522b8, 0xb)
    /usr/lib/golang/src/pkg/net/fd_unix.go:419 +0x343
net.(*UnixListener).AcceptUnix(0xc208072d60, 0x8aa4a0, 0x0, 0x0)
    /usr/lib/golang/src/pkg/net/unixsock_posix.go:293 +0x73
net.(*UnixListener).Accept(0xc208072d60, 0x0, 0x0, 0x0, 0x0)
    /usr/lib/golang/src/pkg/net/unixsock_posix.go:304 +0x4b
lc-lib/admin.(*Listener).Run(0xc2080b9c80)
    BUILD/log-courier-1.3/src/lc-lib/admin/listener.go:114 +0x36c
created by lc-lib/core.(*Pipeline).Start
    BUILD/log-courier-1.3/src/lc-lib/core/pipeline.go:65 +0x98

goroutine 22 [chan receive, 910 minutes]:
lc-lib/registrar.(*Registrar).Run(0xc20809a8c0)
    BUILD/log-courier-1.3/src/lc-lib/registrar/registrar.go:151 +0xd2
created by lc-lib/core.(*Pipeline).Start
    BUILD/log-courier-1.3/src/lc-lib/core/pipeline.go:65 +0x98

goroutine 23 [semacquire, 5102 minutes]:
sync.runtime_Semacquire(0xc2083aa040)
    /usr/lib/golang/src/pkg/runtime/sema.goc:199 +0x30
sync.(*WaitGroup).Wait(0xc208033788)
    /usr/lib/golang/src/pkg/sync/waitgroup.go:129 +0x14b
lc-lib/transports.(*TransportTcp).disconnect(0xc208033760)
    BUILD/log-courier-1.3/src/lc-lib/transports/tcp.go:264 +0x5a
lc-lib/transports.(*TransportTcp).Init(0xc208033760, 0x0, 0x0)
    BUILD/log-courier-1.3/src/lc-lib/transports/tcp.go:162 +0x59
lc-lib/publisher.(*Publisher).Run(0xc2080b01e0)
    BUILD/log-courier-1.3/src/lc-lib/publisher/publisher.go:165 +0x2ce
created by lc-lib/core.(*Pipeline).Start
    BUILD/log-courier-1.3/src/lc-lib/core/pipeline.go:65 +0x98

goroutine 24 [select, 5280 minutes]:
lc-lib/spooler.(*Spooler).sendSpool(0xc2080acb60, 0x769df0)
    BUILD/log-courier-1.3/src/lc-lib/spooler/spooler.go:127 +0x1d7
lc-lib/spooler.(*Spooler).Run(0xc2080acb60)
    BUILD/log-courier-1.3/src/lc-lib/spooler/spooler.go:97 +0x68d
created by lc-lib/core.(*Pipeline).Start
    BUILD/log-courier-1.3/src/lc-lib/core/pipeline.go:65 +0x98

goroutine 25 [select]:
lc-lib/prospector.(*Prospector).Run(0xc20808dc80)
    BUILD/log-courier-1.3/src/lc-lib/prospector/prospector.go:181 +0xda7
created by lc-lib/core.(*Pipeline).Start
    BUILD/log-courier-1.3/src/lc-lib/core/pipeline.go:65 +0x98

goroutine 17 [syscall, 18532 minutes]:
runtime.goexit()
    /usr/lib/golang/src/pkg/runtime/proc.c:1445

goroutine 27 [select, 5280 minutes]:
lc-lib/harvester.(*Harvester).eventCallback(0xc2080289c0, 0x11a6, 0x11db, 0xc20a36a1c0, 0x34)
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:296 +0x84a
lc-lib/harvester.*Harvester.(lc-lib/harvester.eventCallback)·fm(0x11a6, 0x11db, 0xc20a36a1c0, 0x34)
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:84 +0x4e
lc-lib/codecs.(*CodecPlain).Event(0xc2080a2280, 0x11a6, 0x11db, 0xc20a36a1c0, 0x34)
    BUILD/log-courier-1.3/src/lc-lib/codecs/plain.go:52 +0x51
lc-lib/harvester.(*Harvester).harvest(0xc2080289c0, 0xc20805e460, 0x0, 0x0, 0x0)
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:179 +0x72d
lc-lib/harvester.func·001()
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:92 +0x71
created by lc-lib/harvester.(*Harvester).Start
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:94 +0x8b

goroutine 1976 [select, 3800 minutes]:
lc-lib/harvester.(*Harvester).eventCallback(0xc208028a90, 0x0, 0xd8, 0xc20805e0e0, 0xd7)
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:296 +0x84a
lc-lib/harvester.*Harvester.(lc-lib/harvester.eventCallback)·fm(0x0, 0xd8, 0xc20805e0e0, 0xd7)
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:84 +0x4e
lc-lib/codecs.(*CodecPlain).Event(0xc20938a180, 0x0, 0xd8, 0xc20805e0e0, 0xd7)
    BUILD/log-courier-1.3/src/lc-lib/codecs/plain.go:52 +0x51
lc-lib/harvester.(*Harvester).harvest(0xc208028a90, 0xc20805e460, 0x0, 0x0, 0x0)
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:179 +0x72d
lc-lib/harvester.func·001()
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:92 +0x71
created by lc-lib/harvester.(*Harvester).Start
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:94 +0x8b

goroutine 1127 [select, 5232 minutes]:
lc-lib/harvester.(*Harvester).eventCallback(0xc208028d00, 0x0, 0xd8, 0xc20805e620, 0xd7)
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:296 +0x84a
lc-lib/harvester.*Harvester.(lc-lib/harvester.eventCallback)·fm(0x0, 0xd8, 0xc20805e620, 0xd7)
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:84 +0x4e
lc-lib/codecs.(*CodecPlain).Event(0xc209654860, 0x0, 0xd8, 0xc20805e620, 0xd7)
    BUILD/log-courier-1.3/src/lc-lib/codecs/plain.go:52 +0x51
lc-lib/harvester.(*Harvester).harvest(0xc208028d00, 0xc20805e460, 0x0, 0x0, 0x0)
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:179 +0x72d
lc-lib/harvester.func·001()
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:92 +0x71
created by lc-lib/harvester.(*Harvester).Start
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:94 +0x8b

goroutine 1323 [chan send, 5102 minutes]:
lc-lib/transports.(*TransportTcp).sender(0xc208033760)
    BUILD/log-courier-1.3/src/lc-lib/transports/tcp.go:293 +0x255
created by lc-lib/transports.(*TransportTcp).Init
    BUILD/log-courier-1.3/src/lc-lib/transports/tcp.go:251 +0xdb9

goroutine 31 [select, 5280 minutes]:
lc-lib/harvester.(*Harvester).eventCallback(0xc208029380, 0x17f4479e, 0x17f44973, 0xc20a136f00, 0x1d4)
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:296 +0x84a
lc-lib/harvester.*Harvester.(lc-lib/harvester.eventCallback)·fm(0x17f4479e, 0x17f44973, 0xc20a136f00, 0x1d4)
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:84 +0x4e
lc-lib/codecs.(*CodecPlain).Event(0xc2080a2370, 0x17f4479e, 0x17f44973, 0xc20a136f00, 0x1d4)
    BUILD/log-courier-1.3/src/lc-lib/codecs/plain.go:52 +0x51
lc-lib/harvester.(*Harvester).harvest(0xc208029380, 0xc20805e460, 0x0, 0x0, 0x0)
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:179 +0x72d
lc-lib/harvester.func·001()
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:92 +0x71
created by lc-lib/harvester.(*Harvester).Start
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:94 +0x8b

goroutine 2703 [select, 2348 minutes]:
lc-lib/harvester.(*Harvester).eventCallback(0xc208029450, 0x0, 0xd8, 0xc20805e1c0, 0xd7)
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:296 +0x84a
lc-lib/harvester.*Harvester.(lc-lib/harvester.eventCallback)·fm(0x0, 0xd8, 0xc20805e1c0, 0xd7)
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:84 +0x4e
lc-lib/codecs.(*CodecPlain).Event(0xc20938a1b0, 0x0, 0xd8, 0xc20805e1c0, 0xd7)
    BUILD/log-courier-1.3/src/lc-lib/codecs/plain.go:52 +0x51
lc-lib/harvester.(*Harvester).harvest(0xc208029450, 0xc20805e460, 0x0, 0x0, 0x0)
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:179 +0x72d
lc-lib/harvester.func·001()
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:92 +0x71
created by lc-lib/harvester.(*Harvester).Start
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:94 +0x8b

goroutine 128 [select, 5280 minutes]:
lc-lib/harvester.(*Harvester).eventCallback(0xc2080292b0, 0x2c0aa, 0x2c16d, 0xc208029040, 0xc2)
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:296 +0x84a
lc-lib/harvester.*Harvester.(lc-lib/harvester.eventCallback)·fm(0x2c0aa, 0x2c16d, 0xc208029040, 0xc2)
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:84 +0x4e
lc-lib/codecs.(*CodecPlain).Event(0xc208307220, 0x2c0aa, 0x2c16d, 0xc208029040, 0xc2)
    BUILD/log-courier-1.3/src/lc-lib/codecs/plain.go:52 +0x51
lc-lib/harvester.(*Harvester).harvest(0xc2080292b0, 0xc20805e460, 0x0, 0x0, 0x0)
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:179 +0x72d
lc-lib/harvester.func·001()
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:92 +0x71
created by lc-lib/harvester.(*Harvester).Start
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:94 +0x8b

goroutine 3423 [select, 910 minutes]:
lc-lib/harvester.(*Harvester).eventCallback(0xc208029520, 0x0, 0xd8, 0xc20805e2a0, 0xd7)
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:296 +0x84a
lc-lib/harvester.*Harvester.(lc-lib/harvester.eventCallback)·fm(0x0, 0xd8, 0xc20805e2a0, 0xd7)
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:84 +0x4e
lc-lib/codecs.(*CodecPlain).Event(0xc20938a300, 0x0, 0xd8, 0xc20805e2a0, 0xd7)
    BUILD/log-courier-1.3/src/lc-lib/codecs/plain.go:52 +0x51
lc-lib/harvester.(*Harvester).harvest(0xc208029520, 0xc20805e460, 0x0, 0x0, 0x0)
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:179 +0x72d
lc-lib/harvester.func·001()
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:92 +0x71
created by lc-lib/harvester.(*Harvester).Start
    BUILD/log-courier-1.3/src/lc-lib/harvester/harvester.go:94 +0x8b

rax     0xca
rbx     0x8aa580
rcx     0xffffffffffffffff
rdx     0x0
rdi     0x8ab1f0
rsi     0x0
rbp     0xc208010900
rsp     0x7fff942100e8
r8      0x0
r9      0x0
r10     0x0
r11     0x286
r12     0x6cf9c0
r13     0xf6d078dc
r14     0x220541f4
r15     0x84f78f61
rip     0x430ef1
rflags  0x286
cs      0x33
fs      0x0
gs      0x0
```

**Comment by driskell** [comment]
Thanks for the report! I've just confirmed this. There is a race condition if a send() failure occurs. I'll push a fix ASAP.

**Comment by blalor** [comment]
Sweet!  Thanks!

**Comment by blalor** [comment]
How stable is master?  Should I wait for you to do another tag before deploying this?=

**Comment by driskell** [comment]
It should be stable. There's a bulk of tests and checks. Though I normally run it myself in my qa area first before tagging.

I would say this race is so rare you should be OK though. So unless it's an absolute requirement I'd personally stick to 1.3. Once I've starting running develop under some load in my QA I'll then push the tag, then at least you'll know it's been used :+1:

**Comment by blalor** [comment]
It’s not *that* rare; my log event rate’s dropped about 30% since that server crash and hasn’t come back. ;-)

Good to know.  Thanks!=

**Comment by driskell** [comment]
OK I take that back :) I guess when the server crashed it raised a large amount of send() failures. Guess it could be more often in that instance. But hopefully the Logstash crash is rare :)
