### ISSUE TITLE
log-courier logstash output works for a while then stops working

### ISSUE THREAD

**Issue by dsolsona** [driskell/log-courier#136]
I'm currently testing log-courier 1.5 output and it seems you almost got it working :+1:  but still not there.

What I'm seeing is the output working for a few minutes 
```
Pipeline started {:level=>:info, "plugin"=>"input/courier", "port"=>5044}
Starting courier output {:level=>:info, "plugin"=>"input/courier", "port"=>5044}
Connecting {:address=>"aaa.bbb.ccc.ddd", :port=>5044, :level=>:info, "plugin"=>"output/courier", "port"=>5044}
Connected successfully {:level=>:info, "plugin"=>"output/courier", "port"=>5044, "address"=>"aaa.bbb.ccc.ddd"}
```

Then after a while I get this timeout error and it never reconnects again.

```
Timeout occurred {:level=>:warn, "plugin"=>"output/courier", "port"=>5044, "address"=>"aaa.bbb.ccc.ddd"}
Connecting {:address=>"aaa.bbb.ccc.ddd", :port=>5044, :level=>:info, "plugin"=>"output/courier", "port"=>5044, "address"=>"aaa.bbb.ccc.ddd"}
Connection refused - Connection refused {:hint=>"Unknown connection failure", :address=>"aaa.bbb.ccc.ddd", :port=>5044, :level=>:warn, :exception=>Errno::ECONNREFUSED, :backtrace=>["org/jruby/ext/socket/RubyTCPSocket.java:126:in `initialize'", "org/jruby/RubyIO.java:852:in `new'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.5/lib/log-courier/client_tcp.rb:207:in `tls_connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.5/lib/log-courier/client_tcp.rb:55:in `connect'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.5/lib/log-courier/client_tcp.rb:53:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.5/lib/log-courier/client.rb:217:in `run_io'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.5/lib/log-courier/client.rb:215:in `run_io'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.5/lib/log-courier/client.rb:145:in `initialize'"], "plugin"=>"output/courier", "port"=>5044, "address"=>"aaa.bbb.ccc.ddd"}
Connecting {:address=>"aaa.bbb.ccc.ddd", :port=>5044, :level=>:info, "plugin"=>"output/courier", "port"=>5044, "address"=>"aaa.bbb.ccc.ddd"}
Connected successfully {:level=>:info, "plugin"=>"output/courier", "port"=>5044, "address"=>"aaa.bbb.ccc.ddd"}
undefined method `data' for #<LogCourier::PendingPayload:0x12afd8a0> {:hint=>"Unknown error", :level=>:warn, :exception=>NoMethodError, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.5/lib/log-courier/client.rb:255:in `run_io_loop'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.5/lib/log-courier/client.rb:243:in `run_io_loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.5/lib/log-courier/client.rb:221:in `run_io'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.5/lib/log-courier/client.rb:215:in `run_io'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.5/lib/log-courier/client.rb:145:in `initialize'"], "plugin"=>"output/courier", "port"=>5044, "address"=>"aaa.bbb.ccc.ddd"}
Connecting {:address=>"aaa.bbb.ccc.ddd", :port=>5044, :level=>:info, "plugin"=>"output/courier", "port"=>5044, "address"=>"aaa.bbb.ccc.ddd"}
Connected successfully {:level=>:info, "plugin"=>"output/courier", "port"=>5044, "address"=>"aaa.bbb.ccc.ddd"}
undefined method `data' for #<LogCourier::PendingPayload:0x12afd8a0> {:hint=>"Unknown error", :level=>:warn, :exception=>NoMethodError, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.5/lib/log-courier/client.rb:255:in `run_io_loop'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.5/lib/log-courier/client.rb:243:in `run_io_loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.5/lib/log-courier/client.rb:221:in `run_io'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.5/lib/log-courier/client.rb:215:in `run_io'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.5/lib/log-courier/client.rb:145:in `initialize'"], "plugin"=>"output/courier", "port"=>5044, "address"=>"aaa.bbb.ccc.ddd"}
```

**Comment by driskell** [comment]
Yes looks like one or two minor bits still to do there! I'll get a fix up soon.

**Comment by colinmollenhour** [comment]
So is log-courier currently a suitable replacement for logstash-forwarder? Our logstash-forwarder has to reconnect every time events are processed (Read error looking for ACK: EOF) so we are looking for a replacement that is ready for wide deployment.

**Comment by driskell** [comment]
@colinmollenhour Yes it is.
The issue in this ticket is only on the logstash-output-log-courier plugin.

**Comment by dsolsona** [comment]
Awesome. I just finished doing some testing and everything works.

I'll hopefully put this in production in a few days.

Thanks for the quick fix Jason.
