### ISSUE TITLE
log-courier logstash output crash 

### ISSUE THREAD

**Issue by dsolsona** [driskell/log-courier#143]
This is with log-courier 1.6

On the logstash server with the output filter I'm seeing this errors in the logs

```
{:timestamp=>"2015-03-23T17:34:58.615000-0500", :hint=>"Unknown connection failure", :address=>"aaa.bbb.ccc.ddd", :port=>5044, :level=>:warn, :message=>"Connection refused - Connection refused", :exception=>Errno::ECONNREFUSED, :backtrace=>["org/jruby/ext/socket/RubyTCPSocket.java:126:in `initialize'", "org/jruby/RubyIO.java:852:in `new'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/client_tcp.rb:207:in `tls_connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/client_tcp.rb:55:in `connect'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/client_tcp.rb:53:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/client.rb:219:in `run_io'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/client.rb:217:in `run_io'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/client.rb:147:in `initialize'"], "plugin"=>"output/courier", "port"=>5044, "address"=>"aaa.bbb.ccc.ddd"}
{:timestamp=>"2015-03-23T18:06:36.243000-0500", :message=>"Timeout occurred", :level=>:warn, "plugin"=>"output/courier", "port"=>5044, "address"=>"aaa.bbb.ccc.ddd"}
{:timestamp=>"2015-03-23T18:12:06.375000-0500", :message=>"Read error", :error=>"EOFError", :level=>:warn, "plugin"=>"output/courier", "port"=>5044, "address"=>"aaa.bbb.ccc.ddd"}
.....
.....
{:timestamp=>"2015-03-23T18:15:04.747000-0500", :message=>"Read error", :error=>"Connection reset by peer", :level=>:warn, "plugin"=>"output/courier", "port"=>5044, "address"=>"aaa.bbb.ccc.ddd"}
{:timestamp=>"2015-03-23T18:17:16.984000-0500", :hint=>"Unknown connection failure", :address=>"aaa.bbb.ccc.ddd", :port=>5044, :level=>:warn, :message=>"Connection refused - Connection refused", :exception=>Errno::ECONNREFUSED, :backtrace=>["org/jruby/ext/socket/RubyTCPSocket.java:126:in `initialize'", "org/jruby/RubyIO.java:852:in `new'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/client_tcp.rb:207:in `tls_connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/client_tcp.rb:55:in `connect'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/client_tcp.rb:53:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/client.rb:219:in `run_io'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/client.rb:217:in `run_io'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/client.rb:147:in `initialize'"], "plugin"=>"output/courier", "port"=>5044, "address"=>"aaa.bbb.ccc.ddd"}
{:timestamp=>"2015-03-23T18:19:29.208000-0500", :hint=>"Unknown connection failure", :address=>"aaa.bbb.ccc.ddd", :port=>5044, :level=>:warn, :message=>"Connection refused - Connection refused", :exception=>Errno::ECONNREFUSED, :backtrace=>["org/jruby/ext/socket/RubyTCPSocket.java:126:in `initialize'", "org/jruby/RubyIO.java:852:in `new'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/client_tcp.rb:207:in `tls_connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/client_tcp.rb:55:in `connect'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/client_tcp.rb:53:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/client.rb:219:in `run_io'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/client.rb:217:in `run_io'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/client.rb:147:in `initialize'"], "plugin"=>"output/courier", "port"=>5044, "address"=>"aaa.bbb.ccc.ddd"}
{:timestamp=>"2015-03-23T18:19:49.802000-0500", :message=>"Read error", :error=>"EOFError", :level=>:warn, "plugin"=>"output/courier", "port"=>5044, "address"=>"aaa.bbb.ccc.ddd"}
{:timestamp=>"2015-03-23T18:19:49.927000-0500", :message=>"Write error", :error=>"closed SSL engine", :level=>:warn, "plugin"=>"output/courier", "port"=>5044, "address"=>"aaa.bbb.ccc.ddd"}
```

Then on the logstash.err I see
```
LogCourier::ShutdownSignal: LogCourier::ShutdownSignal
         wait at org/jruby/ext/thread/ConditionVariable.java:96
         push at /opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/event_queue.rb:88
         push at /opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/event_queue.rb:87
         loop at org/jruby/RubyKernel.java:1521
         push at /opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/event_queue.rb:84
  synchronize at org/jruby/ext/thread/Mutex.java:149
         push at /opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/event_queue.rb:83
     run_send at /opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/client_tcp.rb:146
      connect at /opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.6/lib/log-courier/client_tcp.rb:68
```

**Comment by dsolsona** [comment]
Do you need more information for this? I can say that this keeps happening every day under very low traffic conditions, quite randomly in time.

**Comment by driskell** [comment]
Let me know if it still happens after the patch.

Looks like the send and receive thread both error at the same time and both try to shut each other down. If one of them gets the shutdown request while it's trying to shutdown the other it doesn't properly handle it. It should do so now.

Do you frequently have network issues though? It's not really normal to receive frequent connection reset or EOFError etc. Is the remote Logstash restarting perhaps?

**Comment by dsolsona** [comment]
Hi Jason,

Sorry for the delay on this. I tested it a few days ago and it's been working without any issue so far.

As for your question about the network issues, I'm using this over the Internet and now that you ask I've noticed that the connection between both logstash servers seem to get some random resets but now it's reconnecting fine.

:+1:
