### ISSUE TITLE
log-courier stops sending data | logstash 1.5.2

### ISSUE THREAD

**Issue by lingyou** [driskell/log-courier#246]
I installed log-courier yesterday, and everything goes fine, but this afternoon, it suddenly stops working.
logstash.log has such content recorded:
>{:timestamp=>"2015-10-29T19:58:29.034000+0800", :hint=>"Unknown error, connection aborted", :peer=>"xx.xx.xx.xx:41153", :level=>:warn, :message=>"Broken pipe - Broken pipe", :exception=>Errno::EPIPE, :backtrace=>["org/jruby/RubyIO.java:1347:in `write_nonblock'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.8.1/lib/log-courier/server_tcp.rb:312:in `send'", "org/jruby/RubyKernel.java:1511:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.8.1/lib/log-courier/server_tcp.rb:310:in `send'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.8.1/lib/log-courier/server.rb:212:in `process_jdat'", "org/jruby/RubyKernel.java:1511:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.8.1/lib/log-courier/server.rb:161:in `process_jdat'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.8.1/lib/log-courier/server.rb:90:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.8.1/lib/log-courier/server_tcp.rb:274:in `process_messages'", "org/jruby/RubyKernel.java:1511:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.8.1/lib/log-courier/server_tcp.rb:250:in `process_messages'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.8.1/lib/log-courier/server_tcp.rb:238:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.8.1/lib/log-courier/server_tcp.rb:204:in `run_thread'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.8.1/lib/log-courier/server_tcp.rb:167:in `run'"]}

There is something wrong about the cpu usage of logstash
when I issue the command  'top -p logstash-pid -H'
I  find that the "|worker" will eat up that core which it runs on.
>Cpu8  :  0.0%us,  0.0%sy, 75.1%ni, 24.9%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+   P COMMAND                                                                                                                                            
 3801 logstash  39  19 17.7g 667m  14m R 99.9  2.1  31:04.45  8 |worker                                                                                                                                             
 3852 logstash  39  19 17.7g 667m  14m S  0.3  2.1   0:00.66  0 LogStash::Runne                                                                                                                                    

This is the input configuration of logstash
> input {
  courier {
    transport => tcp
    port => xxxx
  }
}

This is the configuration of log-courier
>{
    "general": {
        "log syslog": true,
        "log level": "warning",
        "admin enabled": true
    },
        "network": {
            "transport": "tcp",
            "servers": [ "xx.xx.xx.xx:xxxx" ],
            "timeout": 15
        },
        "files": [
        {
            "paths": [
                "/home/logs/xxxx/*.access.log"
            ],
            "fields": { "type": "xxxx" ,
             "project": "xxx"}
        }
        ]
}

I have tried restart logstash and log-courier, no luck, still in the same situation.

Hope for your reply, thanks in advance

**Comment by lingyou** [comment]
I've tried the --debug works when running logstash on the commmand line,
> xxx/bin/logstash --debug -f /logstash/conf/dir/ 

and the problem did not show up again, I will tried again when encounter it next time.
So I close this issue for now.
