### ISSUE TITLE
log-courier 2.x: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sysmonk** [driskell/log-courier#288]
A panic when running -stdin:

```
# tail -10 /var/log/messages | /usr/local/bin/log-courier-new -config /etc/log-courier.dfw.conf -stdin
2016/03/14 16:15:39.447362 Log Courier version 2.0.0-beta1 pipeline starting
2016/03/14 16:15:39.447645 [Random] Randomly selected new endpoint: logstash2.example.com:9001
2016/03/14 16:15:39.448152 Pipeline ready
2016/03/14 16:15:39.449746 Started stdin harvester
2016/03/14 16:15:39.451952 [logstash2.example.com:9001] Attempting to connect to 192.168.0.177:9001 (logstash2.example.com)
2016/03/14 16:15:39.529988 [logstash2.example.com:9001] Connected to 192.168.0.177:9001 (logstash2.example.com)
2016/03/14 16:15:39.530515 [logstash2.example.com:9001] Send is now ready, awaiting new events
2016/03/14 16:15:39.530706 [logstash2.example.com:9001] Starting keepalive timeout
2016/03/14 16:15:39.531023 Timeout timer reset - due at 2016-03-14 16:30:39.530875332 +0000 UTC
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0x4ab3ac]

goroutine 8 [running]:
panic(0x776f20, 0xc82000e0d0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/driskell/log-courier/lc-lib/harvester.(*Harvester).takeMeasurements(0xc8200d6300, 0x3baa91f1, 0x0, 0x0)
        /home/sysmonk/gosrc/src/github.com/driskell/log-courier/lc-lib/harvester/harvester.go:317 +0x2ac
github.com/driskell/log-courier/lc-lib/harvester.(*Harvester).performRead(0xc8200d6300, 0x0, 0x0)
        /home/sysmonk/gosrc/src/github.com/driskell/log-courier/lc-lib/harvester/harvester.go:232 +0xd8
github.com/driskell/log-courier/lc-lib/harvester.(*Harvester).harvest(0xc8200d6300, 0xc8200654a0, 0x0, 0x0, 0x0)
        /home/sysmonk/gosrc/src/github.com/driskell/log-courier/lc-lib/harvester/harvester.go:214 +0x3d4
github.com/driskell/log-courier/lc-lib/harvester.(*Harvester).Start.func1(0xc8200d6300, 0xc8200654a0)
        /home/sysmonk/gosrc/src/github.com/driskell/log-courier/lc-lib/harvester/harvester.go:147 +0x62
created by github.com/driskell/log-courier/lc-lib/harvester.(*Harvester).Start
        /home/sysmonk/gosrc/src/github.com/driskell/log-courier/lc-lib/harvester/harvester.go:152 +0xbd
```

For configs please see #287

**Comment by driskell** [comment]
New measurements in harvester include the current file size to allow monitoring of how far behind a shipper is. This broke stdin.

I'll start writing some tests here.
