### ISSUE TITLE
error in logstash 7

### ISSUE THREAD

**Issue by gupta2007vaibhav** [driskell/log-courier#369]
[2019-05-17T13:46:26,665][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<TypeError: #<Errno::EPIPE:0x1582d59e> is not a string>, :backtrace=>["org/logstash/log/LoggerExt.java:83:in `warn'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/log-courier-1.9.0/lib/log-courier/server_tcp.rb:245:in `run'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/log-courier-1.9.0/lib/log-courier/server_tcp.rb:204:in `run_thread'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/log-courier-1.9.0/lib/log-courier/server_tcp.rb:167:in `block in run'"]}
[2019-05-17T13:46:26,740][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit

**Comment by driskell** [comment]
Looks like there's a warning trying to log, and it would normally just pass the error object to the logger and the logger would convert to string implicitly. Looks like it's not happening in 7 due to moving to a different way of Java logging.

If I find some time I will take a look and convert string first, or if someone offers a patch to driskell/ruby-log-courier where this code resides I can do my best to publish it. I'm mostly at arms reach from these projects, though they've been fairly stable so not needed much attention, so can't guarantee I will get to it any time soon.

Thanks for reporting it though.

**Comment by sysmonk** [comment]
Hi, Any plans for compatibility with LS7.x? Any estimates?

**Comment by driskell** [comment]
I just tested with Logstash 7.3.0 and the current live plugin works flawlessly unless there's a connection error, then it bawls.

I will attempt to push a fix as soon as I can.

I'm sat on some old improvements too so will get those out after.

**Comment by driskell** [comment]
I've pushed 1.10.1

It contains a few gem updates, and the updated ruby-log-courier that should no longer crash on unexpected disconnection errors

Please reopen if any issues.

I tested on 7.3, and 5.1
